<?php
$projects = [
    [
        'id' => 'project1',
        'name' => 'Annex Bios Leidsche Rijn',
        'description' => 'Wij hebben een bioscoop website gemaakt voor een vestiging in Leidsche Rijn. Hierbij moesten wij zorgen dat de website live stond, films te zien waren en stoelen bestelt/gereserveerd konden worden',
        'video' => '',
        'date' => '2024-09-04',
        'link' => 'https://annexbiosleidscherijn.gluwebsite.nl/jnp/annex-bios/',
        'tech' => ['PHP', 'MySQL', 'JavaScript', 'HTML5', 'CSS3'],
    ],
    [
        'id' => 'project2',
        'name' => 'Focus 6',
        'description' => 'Voor dit project heb ik met drie klasgenoten een website gemaakt voor onze klant Arthur, voor zijn bedrijf Focus 6. Hij wilde met deze website delen wat het bedrijf doet. Ook wilde hij de website zelf kunnen bewerken en pagina\'s kunnen toevoegen via een door ons gebouwd CMS.',
        'image' => 'assets/img/focus6.jpeg',
        'image2' => 'assets/img/focus62.png',
        'video' => 'assets/video/focus6Vid.mkv',
        'date' => '2025-09-23',
        'link' => 'https://u230067.gluwebsite.nl/focus6/?view',
        'tech' => ['PHP', 'MySQL', 'JavaScript', 'HTML5', 'CSS3', 'Figma'],
    ],
    [
        'id' => 'project3',
        'name' => 'Tooth Rush',
        'description' => 'Voor dit project moest ik een game maken met een winters sfeertje, en daarvoor heb ik dit spel ontwikkeld. Inspiratie heb ik gehaald uit Subway Surfers.',
        'image' => 'assets/img/toothrush.png',
        'image2' => 'assets/img/toothrush2.png',
        'video' => 'assets/video/toothrushVid.mkv',
        'date' => '2025-12-14',
        'link' => 'https://u230062.gluwebsite.nl/web/toothRush/',
        'tech' => ['JavaScript', 'HTML5', 'CSS3'],
    ],
    [
        'id' => 'project4',
        'name' => 'Happy Herbivore',
        'description' => 'In vier weken heb ik samen met mijn teamgenoot Pebbles voor onze klant Harry een werkend kioskprototype gemaakt voor zijn fictieve bedrijf Happy Herbivore.',
        'image' => 'assets/img/happyHerbivore.jpg',
        'image2' => 'assets/img/happyHerbivore2.png',
        'video' => 'assets/video/happyHerbivoreVid.mkv',
        'date' => '2025-3-14',
        'link' => '',
        'tech' => ['PHP', 'JavaScript', 'HTML5', 'CSS3', 'Figma'],
    ],
    [
        'id' => 'project5',
        'name' => 'Remote Control',
        'description' => 'Dit project was voor een van mijn keuzedelen. Hiervoor moest ik mij verdiepen in specifieke software, waarvoor ik Python had gekozen. In ongeveer drie tot vier weken heb ik een remote control gemaakt met behulp van Python. Wanneer de display op een laptop is geopend en de remote op een ander apparaat actief is, kan ik ervoor zorgen dat er verschillende acties op de laptop plaatsvinden, zoals tekst wijzigen, apps openen en zelfs de laptop afsluiten.',
        'image' => 'assets/img/remoteControl.png',
        'image2' => 'assets/img/remoteControl2.png',
        'video' => 'assets/video/remoteControlVid.mkv',
        'date' => '2025-5-12',
        'link' => '',
        'tech' => ['Python', 'Socket.IO', 'Javascript', 'HTML5', 'CSS3'],
    ]
]; 